### PR TITLE
Test todo list

### PR DESCRIPTION
**Pull request by AnsarIbrahim**
### This PR Contains :
- Test
- Add Test
- Remove Test
- Add Jest Frameworks
- Linters Check
- Mock
- Used JSDOM
- Coverage
- Pair Programming

### CODE REVIEW

**Comment by DeliceLydia** [comment]
## Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that I am not able to run locally
Screen Shot 2023-04-06 at 17 55 45


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Bennyjoez** [comment]
Hello, @DeliceLydia Thank you for the review. Not sure why you were not able to run the tests on your end. However, I was able to run the tests on a separate machine through the following procedure. 
- git clone the repo.
- checkout to the correct branch (Test-todo-list).
- Run npm install.
- Run npm test

I hope this procedure helps. 👩🏾‍💻

**Comment by AnsarIbrahim** [comment]
Hi @DeliceLydia, as my partner has said, the project runs on every other machine we have tested it on. Kindly see the image below:
Untitled

**Review by huseyinbiyik — APPROVED** [review]
Hi team,

## ✔️ Status: APPROVED 🏆 🎉 🎊

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Alt Text



## Highlights
- Add and remove functionality tested 👍 
- DOM mocked for testing 👍 
- Tests are passing 💯 
- Linter set up well and checks pass 🟢
- Github flow followed 👌
- PR description is descriptive 📝

## Optional suggestions
- Great job guys but I couldn't find the delete the task button. It seems you can only delete with Clear All Completed button. I recommend you to add a trash icon to delete each tasks individually like on this [video](https://www.youtube.com/watch?v=AcUd-_Yjjqg) or on like this [project](https://huseyinbiyik.github.io/minimalist/). In this way, you can have a better UX. 👍 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
